
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izzyaiuqlcedbwjcfvwy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6enlhaXVxbGNlZGJ3amNmdnd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2Njg2NDcsImV4cCI6MjA1OTI0NDY0N30.jhVNeXBKpI5OhB6nuBYy-TdEKEQKzD2F7PcbWRBI8UY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
